# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
#HEROKU DEPLOY -----------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: truco_development

production:
  <<: *default
  database: truco_production
  username: truco
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
#HEROKU DEPLOY -----------------------------
